### ISSUE TITLE
The `tf-grid-cli login` command doesn't include `dev` & `qa` as options while selecting the network

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tf-grid-cli#6]
## Describe the bug

The `tf-grid-cli login` command doesn't include `dev` & `qa` as options while selecting the network. however they will work normally if you enter dev or qa as a network value but it also should be mentioned next to (main,test).

## To Reproduce

- Execute `tf-grid-cli login`
- Enter your mnemonics.

## Expected behavior

`dev` & `qa` should also be displayed as a network option.

## Screenshots

![image](https://user-images.githubusercontent.com/101194226/226865287-92b5756e-8176-468e-961f-4fd14b2c24d7.png)

**Comment by xmonader** [comment]
while I agree with the reasoning, but the end user should only care about using mainnet, even testnet is a bit of a stretch. I'll close as won't fix
